[package]
name = "rawk"
version = "0.1.0"
authors = ["Ryan Waskiewicz <ryanwaskiewicz@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
assert_cmd = "1.0.2"
clap = "2.33.0"
env_logger = "0.8.2"
log = "0.4.13"
predicates = "1.0.6"
rustyline = "8.2.0"
