[package]
name = "rawk"
version = "0.1.0"
authors = ["Ryan Waskiewicz <ryanwaskiewicz@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
assert_cmd = "2.0.2"
clap = "2.33.0"
env_logger = "0.9.0"
log = "0.4.14"
predicates = "2.0.3"
rustyline = "9.0.0"
